name: Docker images

on:
  workflow_dispatch:
    
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.400'

      - name: Restore packages
        run: dotnet restore src/Ecommerce.Common

      - name: Build package
        run: dotnet pack src/Services/Account/Account.Web -c Release

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: build and push
        run: |
          docker build ./src/Services/Account/Account.Web -t ghcr.io/fredyyy998/ecommerce/Account:latest
          docker run ghcr.io/fredyyy998/ecommerce/Account:latest
          docker push ghcr.io/fredyyy998/ecommerce/Account:latest
