name: NuGet Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.400'

      - name: Restore packages
        run: dotnet restore src/Ecommerce.Common

      - name: Build package
        run: dotnet pack src/Ecommerce.Common -c Release

      - name: Publish package
        run: |
          dotnet nuget push "src/Ecommerce.Common/Ecommerce.Common.Core/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ secrets.PACKAGE_DEPLOY_KEY  }} --source https://nuget.pkg.github.com/fredyyy998/index.json
      
      - name: Publish package
        run: |
          dotnet nuget push "src/Ecommerce.Common/Ecommerce.Common.Kafka/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ secrets.PACKAGE_DEPLOY_KEY  }} --source https://nuget.pkg.github.com/fredyyy998/index.json
      
      - name: Publish package
        run: |
          dotnet nuget push "src/Ecommerce.Common/Ecommerce.Common.Web/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ secrets.PACKAGE_DEPLOY_KEY  }} --source https://nuget.pkg.github.com/fredyyy998/index.json
