name: NuGet Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.400'

      - name: Restore packages
        run: dotnet restore

      - name: Build package
        run: dotnet pack src/Ecommerce.Common -c Release

      - name: Publish package
        run: |
          dotnet nuget push "src/Ecommerce.Common.Core/bin/Release/Ecommerce.Common.Core.1.0.0.nupkg" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN  }} --source https://nuget.pkg.github.com/fredyyy998/index.json
