name: Docker images

on:
  workflow_dispatch:
    
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.400'
          
      - name: Configure NuGet
        run: dotnet nuget add source --username fredyyy998 --password ${{ secrets.PACKAGE_DEPLOY_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/fredyyy998/index.json"


      - name: Restore packages
        run: dotnet restore Account.Web
        working-directory: src/Services/Account

      - name: Build package
        run: dotnet build Account.Web -c Release
        working-directory: src/Services/Account

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: build and push
        working-directory: src/Services/Account
        run: |
          docker build . -t ghcr.io/fredyyy998/ecommerce/account:latest
          docker run ghcr.io/fredyyy998/ecommerce/account:latest
          docker push ghcr.io/fredyyy998/ecommerce/account:latest
