name: 'TestReport'
on:
  workflow_run:
    workflows: ['UnitTest']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          name: 'UnitTests'
          path: '*.trx'
          reporter: 'dotnet-trx'