name: Unit Test
on: workflow_dispatch

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.400'
          
    - name: Configure NuGet
      run: dotnet nuget add source --username fredyyy998 --password ${{ secrets.PACKAGE_DEPLOY_KEY }} --name github "https://nuget.pkg.github.com/fredyyy998/index.json"

    - name: Build and test Account Service
      run: dotnet test src/Services/Account/Account.Test/Account.Test.csproj --logger "console;verbosity=detailed" --configuration Release

    - name: Build and test Inventory Service
      run: dotnet test src/Services/Inventory/Inventory.Test/Inventory.Test.csproj --logger "console;verbosity=detailed" --configuration Release
