name: UnitTest
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.400'
          
    - name: Configure NuGet
      run: dotnet nuget add source --username fredyyy998 --password ${{ secrets.PACKAGE_DEPLOY_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/fredyyy998/index.json"

    - name: Build and test Account Service
      run: dotnet test src/Services/Account/Account.Test/Account.Test.csproj --logger "trx;LogFileName=$(pwd)/TestResults/Account.trx" --configuration Release

    - name: Build and test Inventory Service
      run: dotnet test src/Services/Inventory/Inventory.Test/Inventory.Test.csproj --logger "trx;LogFileName=$(pwd)/TestResults/Inventory.trx" --configuration Release

    - name: Build and test Shopping Cart Service
      run: dotnet test src/Services/ShoppingCart/ShoppingCart.Test/ShoppingCart.Test.csproj --logger "trx;LogFileName=$(pwd)/TestResults/ShoppingCart.trx" --configuration Release

    - name: Build and test Fulfillment Service
      run: dotnet test src/Services/Fulfillment/Fulfillment.Test/Fulfillment.Test.csproj --logger "trx;LogFileName=$(pwd)/TestResults/Fulfillment.trx" --configuration Release
  
    - name: Display structure of downloaded files
      run: ls -R     
      
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: 'TestResults/*.trx'
        
